import type { Metadata } from "next";
import type { ReactElement } from "react";
import { Suspense } from "react";
import "./globals.css";
import { Analytics } from "@/analytics/analytics";
import { AutoPageview } from "@/analytics/auto-pageview";
import { DevPageviewToggle } from "@/analytics/dev-pageview-toggle";
import { Footer } from "@/components/layout/footer";
import { Header } from "@/components/layout/header";
import { ThemeProvider } from "@/components/theme/theme-provider";
import { Toaster } from "@/components/ui/sonner";
import { websiteConfig } from "@/config/website";
import { NextIntlClientProvider } from "next-intl";
import type { AbstractIntlMessages } from "next-intl";
import { getLocale, getMessages } from "next-intl/server";

export const metadata: Metadata = {
  title: "BlogKit",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: { children: React.ReactNode }): Promise<ReactElement> {
  const locale: string = await getLocale();
  const messages: AbstractIntlMessages = await getMessages();
  return (
    <html lang={locale} suppressHydrationWarning>
      <body className="min-h-screen">
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <NextIntlClientProvider locale={locale} messages={messages}>
            <Suspense fallback={<div className="container mx-auto px-4 py-8">Loading...</div>}>
              <div className="min-h-screen flex flex-col">
                <Header />
                <div className="flex-1">
                  {children}
                </div>
                <Footer />
                {process.env.NODE_ENV === "production" && (
                  <>
                    <Analytics />
                    {websiteConfig.analytics.enableFirstPartyAnalytics && <AutoPageview />}
                  </>
                )}
                {process.env.NODE_ENV !== "production" &&
                  websiteConfig.analytics.enableFirstPartyAnalytics && <DevPageviewToggle />}
              </div>
            </Suspense>
            <Toaster richColors closeButton />
          </NextIntlClientProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}
