name: OpenDeploy DB Push

on:
  workflow_dispatch:
    inputs:
      environment:
        description: Vercel environment to target
        required: true
        default: production
        type: choice
        options: [production, preview]

jobs:
  db-push:
    runs-on: ubuntu-latest
    concurrency:
      group: opendeploy-db-push-${{ github.ref }}
      cancel-in-progress: false
    env:
      VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'pnpm'

      - name: Enable Corepack
        run: corepack enable

      - name: Activate pnpm
        run: corepack prepare pnpm@10.13.1 --activate

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Install Vercel CLI
        run: npm i -g vercel@latest

      - name: Pull env from Vercel
        run: |
          if [ "${{ inputs.environment }}" = "production" ]; then
            vercel env pull .env.production.local --environment production
          else
            vercel env pull .env.preview.local --environment preview
          fi

      - name: DB Push (Drizzle)
        run: |
          if [ "${{ inputs.environment }}" = "production" ]; then
            set -a
            source .env.production.local
            set +a
          else
            set -a
            source .env.preview.local
            set +a
          fi
          pnpm db:push
